### ISSUE TITLE
validation documentation

### ISSUE THREAD

**Issue by peymaneshghi** [phuse-org/valtools#4]
Hey team,

Earlier today, I had a conversation with Ellis and he asked me to raise this here for possible consideration in future.
This framework is designed in such a way that validation documentation is part of the package build. i.e. specifications, test cases, test code, and reports will all live under `vignette/` directory.

As a consequence, it only provides validation evidence for a specific version of the package, in a specific environment, with specific versions of dependent packages, etc. If I want to re-validate my package in a new environment, I should either rebuild (and up-version) the whole package (even if I am not making any changes to the code), or manually re-run validation from  `vignette/` and save the validation documentation elsewhere. Given the fast-moving nature of R environment, many people would probably choose the latter. 

I would therefore like to suggest some flexibility with regards to the location of the `validation/` folder to allow keeping validation documentation separate from the package build. 
If say we place the `validation/` within the `inst/ ` directory instead of `vignette/`, it will allow us to revalidate and redistribute the package without having to rebuild.

**Comment by mariev** [comment]
Thanks for the question @peymaneshghi. You are correct in pointing out that processes can become tricky when distributing `vignette/` files across multiple platforms and/or proprietary systems.

From the description above it sounds like the use case is for individuals to be able to compile the validation report on-demand, using their own computer system, without having to make administrative modifications such as updating the DESCRIPTION. Do I have that correct?

**Comment by peymaneshghi** [comment]
Thanks @mariev. Although my suggestion might potentially cover the use case that you outlined, typically validation of a package will only be truly beneficial if the platform hosting the package is also qualified or validated.
Therefore, rather than individuals on their own computer systems, I am more interested in the admins who look after the controlled platform. They need to keep up with the frequent upgrades of R and R packages, and at the same time, they need to maintain (or at least keep records of) the validation status of our package. For them, being able to re-validate and regenerate validation reports, without having to modify the package, would be a great deal of help.

**Comment by mariev** [comment]
Ahh, so these admins are populating a read-only library location? Or possibly configuring a server resource that multiple users access?  Since you have the option of making packages that are authored at your org available to in uncompressed source form (which skips building source tarballs or binary distributions), there are a couple options for how admins can re-generate validation reports:

1. Run `devtools::build_vignettes( install = TRUE)` on the same uncompressed source to generate the validation report. The validation report gets populated to PACKAGENAME/docs in the source folder in a manner that plays nicely with version control and there is no separate installation step.
2. Install from uncompressed source folders via `remotes::install_*` with argument `build_vignettes = TRUE`. The compiled document gets populated to inst/doc on the destination system (doesn't update source location) as part of the install process.

Now if admins are balking at the inefficiency of running R in the midst of other tasks, it may be helpful to show them how to execute this from the command prompt, via `R script` or `R CMD`. An example of running (2) via command prompt would be: `Rscript -e "devtools::install_local('PACKAGENAME', build_vignettes = TRUE)"`. 

Alternatively, if the admin role is to manage a locked CRAN-like repo i.e. that users access via `install.packages(..., repos = YOUR_LOCAL_REPO)`, the admin can use `R CMD build` (at command prompt) to generate source package (a tarball) where the inst/doc folder is populated using whatever environment is the build is called from. While this doesn't avoid "building" the package, this can be run as a single step (no need to start R,  pre-install the package, then move files around after the vignette pdf is generated). A feature of this is that users are also able to check the source package tarball using `R CMD check` or its variants which will run the Rmd code in inst/doc on the users' system. 

There are also options to leverage c.i. scripts (see documentation from usethis package) to run R commands to automate validation report generation if runners are available at your org.

At this time, my understanding of this project is that we are pursing a "validation at distribution"/"validation at install" paradigm. This is distinct from the traditional "validation *after* install" paradigm. Moving validation code from vignette/ to inst/ appears to be a switch from the former to the latter.

**Comment by mariev** [comment]
closing this because {valtools} now addresses multiple use models:

1. validate on distribute
2. validate on install
3. validate after install
4. validate outside of package
