### ISSUE TITLE
Functionality for scraping authorship

### ISSUE THREAD

**Issue by elimillera** [phuse-org/valtools#41]
Get authorship from validation items by using updates found [here](https://github.com/phuse-org/valtools/pull/38) similar to the functionality [here](https://github.com/phuse-org/valtools/blob/scharp_legacy/R/scrape_func_roxy_blocks.R).

**Comment by thebioengineer** [comment]
Hey @elimillera, I think this is related to #14? @mariev

**Comment by elimillera** [comment]
Sorry I wasn't clear here. I was looking at looking into the rendering of the authorship stuff here

**Comment by thebioengineer** [comment]
By rendering, do you mean generating the tables?

**Comment by elimillera** [comment]
@thebioengineer Right, so the actual calls to kable. Apologies if this is done somewhere. I'm starting to loose the thread a bit on what is done and what is still in the works with current PRs.

**Comment by thebioengineer** [comment]
no worries, we have had a ton floating around!! I don't think that this has been done yet AFAIK. working on the functions that makes the tables pretty is great.

**Comment by mariev** [comment]
Yeah - this issue is partially captured via #14 (although needs to be updated for the config implementation). Noting for our collective memory that:

1.  we should split retrieving info `vt_scrape_` from wrappers that covert to kable `vt_kable`. This allows users the option of formatting to their own preferences
2.  there is some retrieval generics captured via branch `parse_roxygen_generics`  - lets start by comparing that work to the legacy code and go from there

**Comment by mariev** [comment]
Looking at #38 more closely, it appears that this feature is being implemented via `vt_scrape_function_authors`

**Comment by thebioengineer** [comment]
I branched off of #14 when making #38 since this was originally an exploration of a concept. it would need to be updated to use the generics (which I can do)

**Comment by mariev** [comment]
@thebioengineer let's just pull `develop` into #38 and merge that directly.

**Comment by thebioengineer** [comment]
:+1: and then still address function scraping

**Comment by thebioengineer** [comment]
I think this has been resolved and is in develop. Closing, but re-open if you feel as though more needs to be done.
